### ISSUE TITLE
Try to be compatible with multiple versions of ascii

### ISSUE THREAD

**Issue by tormol** [tormol/encode_unicode#9]
I think this should be possible with something like

```toml
[dependencies]
ascii = "0.7-0.9"
```

The only parts this crate use are `AsciiChar as u8` and `ToAsciiChar`, which are unlikely to change.
